language: rust
sudo: false
cache: cargo

rust:
  - nightly-2018-06-20
env:
  global:
    # XXX: begin_test_transaction doesn't play nice over threaded tests
    - RUST_TEST_THREADS=1
    - ROCKET_DATABASE_URL="mysql://travis@127.0.0.1/megaphone"

services:
  - mysql

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS megaphone;'
