[package]
name = "megaphone"
version = "0.1.5"
authors = ["jrconlin <me+crypt@jrconlin.com>"]

[dependencies]
diesel = { version = "1.2", features = ["mysql", "r2d2"] }
diesel_migrations = { version = "1.2", features = ["mysql"] }
failure = "0.1"
lazy_static = "1.0"
mozsvc-common = "0.1"
regex = "1.0"
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = "0.3"
serde = "1.0"
serde_json = "1.0"
slog = { version = "2.2", features = ["nested-values"] }
slog-async = { version = "2.2.0", features = ["nested-values"] }
slog-mozlog-json = "0.1"
slog-term = "2.4"
toml = "0.4"
