[package]
name = "megaphone"
version = "0.1.3"
authors = ["jrconlin <me+crypt@jrconlin.com>"]

[dependencies]
diesel = { version = "1.2", features = ["mysql", "r2d2"] }
diesel_migrations = { version = "1.2", features = ["mysql"] }
failure = "0.1"
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.4"
