[package]
name = "megaphone"
version = "0.1.0"
authors = ["jrconlin <me+crypt@jrconlin.com>"]

[dependencies]
diesel = { version = "1.0", features = ["mysql"] }
dotenv = "0.9"
error-chain = "0.11.0"
hyper = "0.11.18"
hyper-tls = "0.1.2"
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = "0.3"
rusoto_core = "0.31"
rusoto_sns = "0.31"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
websocket = "0.20"
