[package]
name = "megaphone"
version = "0.1.0"
authors = ["jrconlin <me+crypt@jrconlin.com>"]

[dependencies]
diesel = { version = "1.0", features = ["mysql"] }
dotenv = "0.9"
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = "0.3"
serde = "1.0"
serde_json = "1.0"
websocket = "0.20"
