[package]
name = "megaphone"
version = "0.1.0"
authors = ["jrconlin <me+crypt@jrconlin.com>"]

[dependencies]
config = "0.8"
diesel = { version = "1.0", features = ["mysql"] }
dotenv = "0.9"
failure = "0.1"
hyper = "0.11.18"
hyper-tls = "0.1.2"
lazy_static = "1.0"
mysql = "12.1"
r2d2 = "0.8"
r2d2-diesel = "1.0"
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = "0.3"
rusoto_core = "0.31"
rusoto_sns = "0.31"
rusoto_sqs = "0.31"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
websocket = "0.20"
