version: '3'
services:
    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        ports:
            - "4306:3306"
            - "5567:5567"
            - "5568:5568"
        environment:
            #MYSQL_RANDOM_ROOT_PASSWORD: yes
            MYSQL_ROOT_PASSWORD: random
            MYSQL_DATABASE: megaphone
            MYSQL_USER: megaphone
            MYSQL_PASSWORD: test

    app:
        image: mozilla/megaphone
        ports:
          - "8000:8000"
        depends_on:
          - db
        environment:
          ROCKET_DATABASE_URL: mysql://megaphone:test@db:3306/megaphone
          ROCKET_BROADCASTER_AUTH: ${ROCKET_BROADCASTER_AUTH}
          ROCKET_READER_AUTH: ${ROCKET_READER_AUTH}

volumes:
    db_data:

# Applicaiton runs off of port 8000.
# you can test if it's available with
# curl "http://localhost:8000/__heartbeat__"
