debug = true

[database]
host = "localhost"
username = ""
password = ""
port = "3306"
tablename = "megaphone_services"

[aws]
region = "UsWest2"
sns_topic = "arn:aws:sns:us-west-2:927034868273:megaphone_updates"
sqs_prefix = "megaphone_"
